/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Status {
  beforeSetTime: string
  afterSetTime: string
  errNo: number
  errMsg: string
}
export function checkAndSet(): Status
